<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.avaloq.tools.ddk</groupId>
    <artifactId>ddk-core-parent</artifactId>
    <version>17.2.0-SNAPSHOT</version>
    <relativePath>../ddk-core-parent</relativePath>
  </parent>

  <artifactId>com.avaloq.tools.ddk.xtext.check.generator</artifactId>
  <packaging>jar</packaging>

  <dependencies>
    <dependency>
      <groupId>com.avaloq.tools.ddk</groupId>
      <artifactId>com.avaloq.tools.ddk.check.runtime.core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.xtext</groupId>
      <artifactId>org.eclipse.xtext</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.xtext</groupId>
      <artifactId>org.eclipse.xtext.xtext.generator</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>biz.aQute.bnd</groupId>
        <artifactId>bnd-maven-plugin</artifactId>
        <configuration>
          <bnd><![CDATA[
Bundle-SymbolicName: ${project.artifactId};singleton:=true
Bundle-Vendor: Avaloq Group AG
Export-Package: \
  com.avaloq.tools.ddk.xtext.check.generator,\
  com.avaloq.tools.ddk.xtext.check.generator.quickfix
Import-Package: *
          ]]></bnd>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
